"use client";

import { useEffect, useState } from "react";
import { useTranslations } from "next-intl";

interface RuntimeStatus {
  aiRuntime: "CONNECTED" | "ERROR" | "NOT_CONNECTED";
  geminiStatus: string;
  lastExecutionId: string | null;
  modelName: string | null;
  firestoreStatus: "CONNECTED" | "NOT_CONNECTED";
  agentMode: string;
  aiEnabled: boolean;
}

/**
 * AI Runtime status indicator.
 *
 * Shows CONNECTED only when a real successful ADK/Gemini execution has occurred.
 * CONNECTED means a real proposal was generated by Gemini.
 * ERROR means the connection attempt failed.
 * NOT_CONNECTED means AI is not enabled or no execution has happened yet.
 *
 * Does NOT expose internal chain-of-thought.
 */
export function AIRuntimeStatus() {
  const t = useTranslations("aiRuntime");
  const [status, setStatus] = useState<RuntimeStatus | null>(null);

  const fetchStatus = async () => {
    try {
      const res = await fetch("/api/demo");
      if (res.ok) {
        const data = await res.json();
        setStatus({
          aiRuntime: data.aiRuntime ?? "NOT_CONNECTED",
          geminiStatus: data.geminiStatus ?? "NOT_CONNECTED",
          lastExecutionId: data.lastExecutionId ?? null,
          modelName: data.modelName ?? null,
          firestoreStatus: data.firestoreStatus ?? "NOT_CONNECTED",
          agentMode: data.agentMode ?? "DEV",
          aiEnabled: data.aiEnabled ?? false,
        });
      }
    } catch {
      setStatus((prev) => ({
        aiRuntime: "ERROR",
        geminiStatus: "ERROR",
        lastExecutionId: prev?.lastExecutionId ?? null,
        modelName: prev?.modelName ?? null,
        firestoreStatus: prev?.firestoreStatus ?? "NOT_CONNECTED",
        agentMode: prev?.agentMode ?? "DEV",
        aiEnabled: prev?.aiEnabled ?? false,
      }));
    }
  };

  useEffect(() => {
    const initialLoad = window.setTimeout(() => void fetchStatus(), 0);
    const interval = setInterval(fetchStatus, 10000);
    return () => {
      window.clearTimeout(initialLoad);
      clearInterval(interval);
    };
  }, []);

  if (!status) return null;

  const isConnected = status.aiRuntime === "CONNECTED";
  const isError = status.aiRuntime === "ERROR";

  return (
    <div className="flex items-center gap-2 text-xs font-mono">
      <span className="text-neutral-500">{t("label")}:</span>
      <span
        className={
          isConnected
            ? "text-green-400 font-semibold"
            : isError
            ? "text-red-400 font-semibold"
            : "text-neutral-500"
        }
      >
        {isConnected
          ? t("connected")
          : isError
          ? t("error")
          : t("notConnected")}
      </span>
      {isConnected && status.lastExecutionId && (
        <span className="text-neutral-600 hidden md:inline" title={status.lastExecutionId}>
          [{status.lastExecutionId.slice(0, 8)}...]
        </span>
      )}
      {isConnected && status.modelName && (
        <span className="text-neutral-500 hidden lg:inline">{status.modelName}</span>
      )}
    </div>
  );
}
